WestEdu.web/Models/Course.cs
namespace WestEdu.web.Models;

public class Course{
    public Guid CourseId { get; set; } = Guid.NewGuid();
    public string CourseName { get; set; } = "";

    public int CourseNumber {get;set;}


    public DateTime StartDate { get; set; }

    public DateTime EndDate { get; set; }

    public double CoursePrice { get; set; }

}

WestEdu.web/Models/ShopCart.cs
namespace WestEdu.web.Models;
public class ShopCart{
    public double Finalprice {get;set;}

    public List<Course> CoursesToBuy { get; set; } = new List<Course>();


    public List<Course> GetMyItems(){
        return CoursesToBuy;
    }
}

WestEdu.web/Models/Teacher.cs
namespace WestEdu.web.Models;


public class Teacher{
    public long SocialSecurityNumber { get; set; }
    public string FirstName { get; set; } = "";

    public string LastName { get; set; } = "";
    public string profilepic {get;set;} = "";


    public List<Course> myCourses {get;set;} = new List<Course>();

    public List<Course> GetAllCourses(){
        return myCourses;
    }
 
}

WestEdu.web/Controllers/CourseController.cs
using System.IO;
using Microsoft.AspNetCore.Mvc;

using WestEdu.web.Models;

namespace WestEdu.web.Controllers
{

 
    public class CourseController : Controller
    {
        List<Course> Kurser = new List<Course>();
        public IActionResult Index()
        {

            Kurser = new List<Course>{
                new Course{CourseId = Guid.NewGuid(), CourseName = "MVC ASP.NET med Micheal", StartDate = DateTime.Now.AddDays(15), EndDate = DateTime.Now.AddMonths(1), CourseNumber = 2342, CoursePrice = 5500},
                new Course{CourseId = Guid.NewGuid(), CourseName = "IT-Säkerhet", StartDate = DateTime.Now.AddDays(30), EndDate = DateTime.Now.AddMonths(2), CourseNumber = 2352, CoursePrice = 2500}
            };

            
            return View("Index", Kurser);
        }

     [HttpGet("Course/{pdfID}")]
     public IActionResult Download(int pdfID)
     {  
        var filepath = $"wwwroot/pdf/{pdfID.ToString()}.pdf";
        if(System.IO.File.Exists(filepath)){
            return File(System.IO.File.ReadAllBytes(filepath), "application/pdf", System.IO.Path.GetFileName(filepath));
        }else{
            return RedirectToAction("Index");
        }

    
       

       
        
        
        
      
     }
    

    }
}

WestEdu.web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;


namespace WestEdu.web.Controllers;

public class HomeController : Controller
{

     public IActionResult Index()
    {
    
        return View("Index");
    }
 
}

WestEdu.web/Controllers/ShopCartController.cs
using Microsoft.AspNetCore.Mvc;

using WestEdu.web.Models;

namespace WestEdu.web.Controllers
{

    public class ShopCartController : Controller
    {
   

        public IActionResult Index()
        {
            ShopCart b1 = new ShopCart();

            b1.CoursesToBuy.Add(new Course{CourseName="MVC ASP.NET med Micheal", CoursePrice = 5500});
            b1.CoursesToBuy.Add(new Course{CourseName="IT-Säkerhet", CoursePrice = 2500});


            var allItems = new List<ShopCart>();
            allItems.Add(
                b1
            );
            return View("Index", allItems);
        }

        [Route("ShopCart/{FinalPrice}")]
        public IActionResult Checkout(int finalprice){
            
            return View("Checkout");
        }




    }
}

WestEdu.web/Controllers/TeacherController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;

using Microsoft.AspNetCore.Mvc;

using WestEdu.web.Models;

namespace WestEdu.web.Controllers
{

    public class TeacherController : Controller
    {

        public IActionResult Index()
        {

            //Michael
            var Michael = new Teacher();

            Michael.myCourses.Add(new Course
            {
                CourseName = "MVC ASP.NET",
            });

            Michael.FirstName = "Micheal";

            Michael.LastName = "Gustavsson";

            Michael.profilepic = "https://images.unsplash.com/photo-1457449940276-e8deed18bfff?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80";


            //Kalle
            var Kalle = new Teacher();
            Kalle.myCourses.Add(new Course
            {
                CourseName = "IT-Säkerhet"
            });

            Kalle.FirstName = "Kalle";

            Kalle.LastName = "Halvarsson";

            Kalle.profilepic = "https://images.unsplash.com/photo-1497316730643-415fac54a2af?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=764&q=80";

            var allTeachers = new List<Teacher>{
                Michael,
                Kalle
            };
            
            return View("Index", allTeachers);
        }

    }
}

WestEdu.web/Views/Course/Index.cshtml
@{
    ViewData["Title"] = "Våra kurser för 2022";
}
@model IList<WestEdu.web.Models.Course>



<h1 class="title-frontpage"> Våra kurser här nedan</h1>



<div class="card-wrapper"> @foreach (var course in Model){

    <div class="cardView">
        <div class="card-content">

            <h4>@course.CourseName</h4>
            <p>KursID: <p class="course-id">@course.CourseId</p></p>
            <p>Kursnummber: @course.CourseNumber</p>
            <p>Startdatum: @course.StartDate.ToString("MM/dd/yyyy")</p>
            <p>Slutdatum: @course.EndDate.ToString("MM/dd/yyyy")</p>
            <p class="price-margin">Pris: @course.CoursePrice kr</p>
            <i class="fa-solid fa-file-pdf">
            </i>
            <a asp-action="Download" asp-controller="Course" asp-route-pdfId=@course.CourseNumber>Ladda ner kursPdf</a>
            @* @Html.ActionLink("Ladda ner kursPDF","Download","Course", new { pdfID = @course.CourseNumber }, null); *@
           
        </div>
   
    </div>
    
    
    }</div>

WestEdu.web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}






<div class="landing">
    <div class="content">
        <h1 class="title-frontpage-start"> Välkommen till Westcoasteducation</h1>
        <h4>--- Vi gör det möjligt ---</h4>
    </div>

</div>
    

WestEdu.web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="~/css/styles.css">
    <script src="https://kit.fontawesome.com/5605743a65.js" crossorigin="anonymous"></script>
    <title>@ViewData["Title"] - Westeducation </title>
</head>

<body>
    <header>
        <nav class="navigation-bar">
            <ul>
                <li class="our-classes-button-logo">
                    <i class="fa-solid fa-graduation-cap"></i>
                </li>
                <li class="our-classes-button">
                    @Html.ActionLink("Hem","Index","Home")
                </li>
                <li class="our-classes-button">

                    @Html.ActionLink("Våra kurser", "Index","Course")
                </li>
                <li class="our-classes-button">

                    @Html.ActionLink("Vi som jobbar här", "Index","Teacher")
                </li>

                <li class="basket">
                    <a href="@Url.Action("Index","ShopCart")">
                        <i class="fa-solid fa-basket-shopping fa-xl">
                        </i></a>
                    
                    </li>
            </ul>

        </nav>
    </header>
    @await Html.PartialAsync("_WeeklyDeals")

    <main>
        @RenderBody()
    </main>

</body>

</html>

WestEdu.web/Views/Shared/_WeeklyDeals.cshtml
<div class="alert">
    <div class="alert-success">
    <h3>50% på alla kurser</h3> 
    <h4>Endast till @DateTime.Now.AddDays(4).ToString("MM/dd/yyyy")</h4>
    </div>
</div>

WestEdu.web/Views/ShopCart/Checkout.cshtml
<h1 class="title-frontpage"> Tack för ditt köp!</h1>

WestEdu.web/Views/ShopCart/Index.cshtml
@{
    ViewData["Title"] = "Din kundkorg";
}
@model IList<WestEdu.web.Models.ShopCart>


<h1 class="title-frontpage">

  <p>Du har köpt kurserna </p>
  @foreach(var item in Model){

    
    foreach(var o in item.GetMyItems()){
        <p> @o.CourseName </p>
        <p> @o.CoursePrice </p>
        
    }
  }

  <p> Totalt 8000 kronor</p>
</h1>

@{int price = 6300;}
<h3 class="title-frontpage"> <a asp-action="checkout" asp-route-finalprice=@price> Betala med PayPal<i class="fa-brands fa-paypal"></i></a></h3>

WestEdu.web/Views/Teacher/Index.cshtml
@{
    ViewData["Title"] = "Vi som jobbar här!";
}

@model IList<WestEdu.web.Models.Teacher>

<div class="card-wrapper"> @foreach (var teacher in Model)
    {

        <div class="cardView">
            <div class="card-content">
                <img src="@teacher.profilepic" alt="" srcset="" />
                <p>@teacher.FirstName</p>
                <p>@teacher.LastName</p>
                @foreach(var courses in @teacher.GetAllCourses()){
                    
                    <a href="@Url.Action("Index","Course")">@courses.CourseName</a>
                }



            </div>
        </div>


    }
</div>